version: '3.2'

services:
  web:
    image: nginx:latest
    container_name: web
    restart: "on-failure"
    ports:
      - 80:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  client:
    build:
      context: ./FE
    container_name: client
    restart: "on-failure"
    expose:
      - 3000
    volumes:
      - './FE:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    working_dir: /home/ubuntu/storyBook
    user: "root"
    ports:
      - 8181:8080
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  spring:
    build:
      context: ./BE
    container_name: spring
    ports:
      - 8080:8080
    restart: always
    environment:
      env_file: .env
